render_devices: auto
update_branch: beta
ui:
  open_browser_on_start: false
model:
  stable-diffusion: sd_xl_base_1.0
model_vae: sdxl_vae
vram_usage_level: balanced
net:
  listen_to_network: true
  listen_port: 9000
force_save_path: "/data/easy-diffusion-images"
test_diffusers: true
daily_quota: 30
num_outputs: 1
block_nsfw: true